### ISSUE TITLE
Can't show "local data" without network connection

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/CellMapper-Android-App#88]
# Impact Version

* CellMapper: App Version: 5.1.1
* Phone Model: Samsung Galaxy S3 and Google Nexus 5x
* Language: en

# Steps to reproduce
Turn off all network connections
Enter cellmaper map, noting the base map data will cache fine depending on settings.
Click to change provider to "[x] Current provider [x] Local Data"

# Current behavior
You get a java "UnknownHostException", and can never select "local data".

# Expected behavior
Expected to see the local data.  If I reverse the sequence, selecting local data while there is a wireless connection, I can then remove the wireless connection and still browse the local data.

# Video/Screenshot link (optional)
On request.

-----------------------------------------------------------------------------
Why do I want this?  Later this year I wish to map towers in an area where I won't have reliable coverage.  Having offline ability to see the locally cached data on a locally cached map is helpful.

Furthermore, for 1XRTT towers which send lat/long, the "local data" does not appear to be the lat/long sent by the tower.

**Comment by zivan56** [comment]
I haven't been able to reproduce this.  I turned off wifi and mobile data, and selected the two boxes on the map, and pressed OK.  The local data then loaded.
Are you saying that the popup covers the local data box?  That shouldn't be the case, as you can click through the popup.
Verified on both a Galaxy S7 and Moto G5 Plus.
For CDMA, I was told by most users to ignore lat/lng, as fake co-ordinates are sent by the majority of large networks with your approximate location instead of the tower location.  If you can confirm which networks do indeed send the right ones, I can potentially use those.

**Comment by brycenesbitt** [comment]
For me, the popup never comes up (it is probably trying to load the list of providers to build the pulldown boxes).

**Comment by brycenesbitt** [comment]
For 1xRTT towers, would be interesting to at least see the advertised address.  For the few towers I've tried it was helpful.

**Comment by brycenesbitt** [comment]
Can you reproduce this yet?
It's 100% here, every time.

**Comment by zivan56** [comment]
It already displays CDMA tower locations broadcast (at least the current tower).
The bug you are seeing is something to do with the map and not data most likely, it should be fixed in the next beta.

**Comment by brycenesbitt** [comment]
The bug I am reporting is an Android specific mobile app bug, and not a map
bug.

**Comment by zivan56** [comment]
Did you try the beta?
Yes, the app has a map...

**Comment by brycenesbitt** [comment]
The bug is not in the beta web map.
The bug is in the current Android app.

**Comment by brycenesbitt** [comment]
This is still present in Beta Android 5.1.3 (8/29/2017)
It happens 100% of the time.

**Comment by zivan56** [comment]
This seems to be a phone specific (UI?) issue, as I cannot reproduce it.
There was a bug that made locally calculated data disappear as soon as the map was touched, but that has been fixed.
Does this happen with CDMA only?

**Comment by brycenesbitt** [comment]
This happens on LTE, UMTS, GSM and CDMA.
This happens on a Samsung Galaxy S3, a Nexus 5, and two different Nexus 5X phones.
It happens 100% of the time when I have tested.

Step 1: Enter map mode.
Step 2: Turn off all network connections (no wifi, no cellular). Or, enter a tunnel.
Step 3: Touch the map away from a cell tower pin, to bring up the data source dialog box.  At this point Cellmaper makes an API call, which fails.  It is not possible to select "show local data".

**Comment by zivan56** [comment]
Fixed in latest version.
